---
- hosts: web_servers
  become: yes
  tasks:
    - name: Install Node.js
      apt:
        name: nodejs
        state: present
        update_cache: yes

    - name: Install npm (Node.js package manager)
      apt:
        name: npm
        state: present

    - name: Clone the Node.js app from GitHub
      git:
        repo: 'https://github.com/Guberapandian/gubera-node.git'
        dest: /var/www/node-app
        version: master

    - name: Install Node.js dependencies
      npm:
        path: /var/www/node-app
        state: present

    - name: Create systemd service for Node.js app
      copy:
        dest: /etc/systemd/system/node-app.service
        content: |
          [Unit]
          Description=Node.js App
          After=network.target

          [Service]
          ExecStart=/usr/bin/node /var/www/node-app/app.js
          Restart=always
          User=nobody
          Group=nogroup
          Environment=PATH=/usr/bin:/usr/local/bin
          Environment=NODE_ENV=production
          WorkingDirectory=/var/www/node-app

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd to apply the new service
      systemd:
        daemon_reload: yes

    - name: Enable and start the Node.js app service
      systemd:
        name: node-app
        state: started
        enabled: yes
